version: '3.7'

services:
  iris:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    image: iris:workshop
    container_name: iris-python
    command: --check-caps false
    ports:
    - "52773:52773"
    - "1972:1972"
    volumes:
    - .:/app